export const mockCVData = [
  {
    id: 1,
    nombre: "Juan",
    apellido: "Pérez",
    edad: '35',
    email: "juan.perez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Buenos Aires, Argentina",
    domicilio: "Calle Falsa 123",
    estudios: "Gastronomía en Instituto Argentino de Gastronomía",
    idiomas: ["Español", "Inglés"],
    descripcion: "Chef con 10 años de experiencia en cocina internacional.",
    categorias: ["Chef Ejecutivo", "Cocina Internacional", "Gestión de Cocina"],
    genero: "Masculino",
    pais: "Argentina",
    creacion: "2023-11-03",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 2,
    nombre: "María",
    apellido: "Gómez",
    edad: '42',
    email: "maria.gomez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Rosario, Argentina",
    domicilio: "Avenida Siempre Viva 742",
    estudios: "Técnico en Gastronomía",
    idiomas: ["Español"],
    descripcion: "Especialista en repostería y pastelería fina.",
    categorias: ["Repostero", "Pastelería Fina", "Decoración de Tortas"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2023-11-01",
    nivelEducacion: "Terciario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "No"
  },
  {
    id: 3,
    nombre: "Carlos",
    apellido: "Ramírez",
    edad: '64',
    email: "carlos.ramirez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Córdoba, Argentina",
    domicilio: "Las Flores 312",
    estudios: "Diplomado en Cocina Gourmet",
    idiomas: ["Español", "Francés"],
    descripcion: "Chef experto en cocina gourmet y molecular.",
    categorias: ["Cocina Molecular", "Gourmet", "Desarrollo de Menú"],
    genero: "Masculino",
    pais: "Argentina",
    creacion: "2023-10-30",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 4,
    nombre: "Lucía",
    apellido: "Martínez",
    edad: '29',
    email: "lucia.martinez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Mendoza, Argentina",
    domicilio: "Boulevard San Martín 456",
    estudios: "Especialista en Cocina Italiana",
    idiomas: ["Español", "Italiano"],
    descripcion: "Amante de la cocina italiana con experiencia en pastas y pizzas artesanales.",
    categorias: ["Chef de Pastas", "Cocina Italiana"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2023-10-28",
    nivelEducacion: "Terciario",
    experienciaAnios: "Más de 3 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 5,
    nombre: "Diego",
    apellido: "Fernández",
    edad: '38',
    email: "diego.fernandez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Salta, Argentina",
    domicilio: "Calle de la Paz 789",
    estudios: "Certificación en Parrilla y Asado",
    idiomas: ["Español"],
    descripcion: "Especialista en parrilla y asado argentino con 15 años de experiencia.",
    categorias: ["Asador", "Parrilla", "Carne a las brasas"],
    genero: "Masculino",
    pais: "Argentina",
    creacion: "2023-10-20",
    nivelEducacion: "Secundario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "No"
  },
  {
    id: 6,
    nombre: "Sofía",
    apellido: "Rodríguez",
    edad: '32',
    email: "sofia.rodriguez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Neuquén, Argentina",
    domicilio: "Ruta del Vino 123",
    estudios: "Especialista en Vinos y Maridajes",
    idiomas: ["Español", "Inglés"],
    descripcion: "Sommelier con vasta experiencia en vinos argentinos y maridajes gourmet.",
    categorias: ["Sommelier", "Vinos", "Maridaje"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2024-11-05",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 7,
    nombre: "Laura",
    apellido: "Gutiérrez",
    edad: '47',
    email: "laura.gutierrez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Santa Fe, Argentina",
    domicilio: "Calle Principal 999",
    estudios: "Pastelería en Escuela Internacional de Cocina",
    idiomas: ["Alemán"],
    descripcion: "Pastelera especializada en postres internacionales y repostería fina.",
    categorias: ["Pastelería", "Postres Internacionales"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2024-11-01",
    nivelEducacion: "Primario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 8,
    nombre: "Miguel",
    apellido: "López",
    edad: '50',
    email: "miguel.lopez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "San Juan, Argentina",
    domicilio: "Ruta 40 Sur 1023",
    estudios: "Chef Ejecutivo en Cocina de Autor",
    idiomas: ["Español"],
    descripcion: "Chef con enfoque en cocina de autor y técnicas de fusión.",
    categorias: ["Chef Ejecutivo", "Cocina de Autor"],
    genero: "Masculino",
    pais: "Perú",
    creacion: "2024-10-15",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "No"
  }, {
    id: 9,
    nombre: "Ana",
    apellido: "Torres",
    edad: '40',
    email: "ana.torres@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "La Plata, Argentina",
    domicilio: "Avenida del Sol 234",
    estudios: "Maestría en Cocina Vegetariana",
    idiomas: ["Español", "Inglés"],
    descripcion: "Chef vegetariana con experiencia en cocina saludable.",
    categorias: ["Cocina Vegetariana", "Saludable"],
    genero: "Femenino",
    pais: "Brasil",
    creacion: "2023-10-15",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 10,
    nombre: "Luis",
    apellido: "Mendoza",
    edad: '36',
    email: "luis.mendoza@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Mar del Plata, Argentina",
    domicilio: "Paseo de los Pinos 789",
    estudios: "Especialización en Cocina Mediterránea",
    idiomas: ["Español", "Italiano"],
    descripcion: "Chef especializado en cocina mediterránea y mariscos.",
    categorias: ["Cocina Mediterránea", "Mariscos"],
    genero: "Masculino",
    pais: "Brasil",
    creacion: "2023-10-05",
    nivelEducacion: "Primario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "No"
  },
  {
    id: 11,
    nombre: "Clara",
    apellido: "Suárez",
    edad: '28',
    email: "clara.suarez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "San Luis, Argentina",
    domicilio: "Calle Jardín 456",
    estudios: "Diploma en Pastelería Creativa",
    idiomas: ["Español"],
    descripcion: "Pastelera creativa enfocada en postres innovadores.",
    categorias: ["Pastelería Creativa", "Innovación en Postres"],
    genero: "Femenino",
    pais: "Chile",
    creacion: "2024-10-01",
    nivelEducacion: "Terciario",
    experienciaAnios: "Más de 3 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 12,
    nombre: "Pablo",
    apellido: "Núñez",
    edad: '45',
    email: "pablo.nunez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Chaco, Argentina",
    domicilio: "Ruta Provincial 12",
    estudios: "Certificación en Asado y Parrilla",
    idiomas: ["Español"],
    descripcion: "Chef experto en carnes y parrilla tradicional argentina.",
    categorias: ["Asador", "Carnes"],
    genero: "Masculino",
    pais: "Italia",
    creacion: "2024-09-20",
    nivelEducacion: "Secundario",
    experienciaAnios: "Más de un año",
    disponibilidadViajar: "No"
  },
  {
    id: 13,
    nombre: "Juliana",
    apellido: "Ramírez",
    edad: '31',
    email: "juliana.ramirez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Corrientes, Argentina",
    domicilio: "Avenida Central 800",
    estudios: "Gastronomía en Universidad Nacional",
    idiomas: ["Español", "Inglés"],
    descripcion: "Chef con conocimientos en cocina molecular y fusión.",
    categorias: ["Cocina Molecular", "Fusión"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2024-09-15",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 14,
    nombre: "Martín",
    apellido: "Herrera",
    edad: '55',
    email: "martin.herrera@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "San Juan, Argentina",
    domicilio: "Pasaje San Martín 1245",
    estudios: "Experto en Panadería",
    idiomas: ["Español"],
    descripcion: "Maestro panadero con amplia experiencia en panadería artesanal.",
    categorias: ["Panadería", "Artesanal"],
    genero: "Masculino",
    pais: "Argentina",
    creacion: "2024-09-05",
    nivelEducacion: "Secundario",
    experienciaAnios: "Menos de un año",
    disponibilidadViajar: "No"
  },
  {
    id: 15,
    nombre: "Nicolás",
    apellido: "González",
    edad: '34',
    email: "nicolas.gonzalez@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Santa Cruz, Argentina",
    domicilio: "Calle Patagonia 402",
    estudios: "Especialización en Cocina Patagónica",
    idiomas: ["Español"],
    descripcion: "Chef especializado en cocina patagónica y productos regionales.",
    categorias: ["Cocina Patagónica", "Regional"],
    genero: "Masculino",
    pais: "Argentina",
    creacion: "2024-08-30",
    nivelEducacion: "Terciario",
    experienciaAnios: "Más de 10 años",
    disponibilidadViajar: "Sí"
  },
  {
    id: 16,
    nombre: "Paula",
    apellido: "Vega",
    edad: '30',
    email: "paula.vega@example.com",
    imagen: "https://via.placeholder.com/150",
    ubicacion: "Misiones, Argentina",
    domicilio: "Ruta Nacional 14",
    estudios: "Certificación en Pastelería Internacional",
    idiomas: ["Español", "Francés"],
    descripcion: "Pastelera con experiencia en postres franceses e internacionales.",
    categorias: ["Pastelería Internacional", "Postres"],
    genero: "Femenino",
    pais: "Argentina",
    creacion: "2024-08-15",
    nivelEducacion: "Universitario",
    experienciaAnios: "Más de 5 años",
    disponibilidadViajar: "Sí"
  },
];
